### ISSUE TITLE
Push Mechanism(WebHook) Application

### ISSUE THREAD

**Issue by toanle1991** [minchao/shopee-php#19]
Hello,
The first thanks for share this library.
I have one question when i try verify for webhook at shopee i can not, so in this library have support?
or can you help me make one simple php code for that ?
Thanks!

**Comment by rmdhfz** [comment]
Hi @minchao 

When will the push mechanism launch ?

**Comment by minchao** [comment]
Hi @toanle1991 @rmdhfz 

Sorry for late reply.

Below is a simple webhook example, you can easily use the [SignatureGenerator](https://github.com/minchao/shopee-php/blob/0.1.0/src/SignatureGenerator.php) of version 0.1.0 to verify incoming push content. But currently I don't have a test environment to verify it, if have any problems, please feel free to contact me :)

https://github.com/minchao/shopee-php/blob/e6b64b7f599f98adf6f9d20598ea79b43d210ed3/examples/webhook/webhook.php#L19-L33

**Comment by rmdhfz** [comment]
Thank you @minchao
