### ISSUE TITLE
Get an orders with status "pickup_pending"

### ISSUE THREAD

**Issue by ewwink** [minchao/shopee-php#20]
Currently I use `orders.GetOrdersByStatus`  with order status `READY_TO_SHIP` but the results is mixed between orders that has tracking number and no, in shopee seller center we can see orders that still need to be processed in `/portal/sale?shipping_center_status=pickup_pending&sort_type=0&type=toship`

Can I use the API to get an orders with status `pickup_pending` without check it one by one using `orders.GetOrderDetails` ?

**Comment by rmdhfz** [comment]
Hi @ewwink ,

Based on the Documentation, there are only:
ALL / UNPAID / READY_TO_SHIP / COMPLETED / IN_CANCEL / CANCELLED / TO_RETURN

https://open.shopee.com/documents?module=4&type=1&id=398
