### ISSUE TITLE
Install this package error on Laravel 7 & 8

### ISSUE THREAD

**Issue by yahyaefendy** [minchao/shopee-php#25]
I am tried install this package, but i has error message

_Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^6.3.1|^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0]_

How to resolved this error. Thanks

**Comment by minchao** [comment]
Hi @yahyaefendy 

The version range of `guzzlehttp/guzzle` has been updated.
Please try the version `0.0.11` again.

Thanks for reporting.

**Comment by yahyaefendy** [comment]
Thank @minchao 

This is resolved for me
