### ISSUE TITLE
Shopee return 'error_params' for getOrdersList function

### ISSUE THREAD

**Issue by ken-ywk** [minchao/shopee-php#5]
Hi, I'm not sure what's wrong with getOrdersList function as the shopee api return 'error_params'. It's beyond my capability to troubleshoot. Hope you can help. Thanks.
https://open.shopee.com/documents?module=4&type=1&id=399

`$response = $client->order->getOrdersList();
print_r($response);`

`
[data:Shopee\ResponseData:private] => Array
  (
   [error] => error_params
)`

**Comment by ken-ywk** [comment]
Hi yes I've checked.
I echoed $jsonBody in client->newRequest
and it is same as your example
{"partner_id":12345,"shopid":67890,"timestamp":1539168484}

**Comment by ken-ywk** [comment]
Hi, it seems either
create_time_from & create_time_to
or
update_time_from & update_time_to
must be included for success call.

**Comment by kyawsoekhaing** [comment]
> Hi, it seems either
> create_time_from & create_time_to
> or
> update_time_from & update_time_to
> must be included for success call.

can anyone help me how to generate create_time_from  and create_time_to?

what is the format ?

**Comment by minchao** [comment]
@kyawsoekhaing It's Unix time

**Comment by BroYoutMrr** [comment]
{"error": "error_params"}

**Comment by BroYoutMrr** [comment]
{"error": "error_params"}

**Comment by BroYoutMrr** [comment]
{"error": "error_params"}

**Comment by BroYoutMrr** [comment]
{"partner_id":12345,"shopid":67890,"timestamp":1539168484}

**Comment by BroYoutMrr** [comment]
{"partner_id":12345,"shopid":67890,"timestamp":1539168484}
